-- Table Department
CREATE TABLE DEPARTMENT (
    ID_DEPARTMENT INT PRIMARY KEY,
    NAME VARCHAR(155)
);

-- Table employee
CREATE TABLE EMPLOYEE (
    ID_EMPLOYEE INT PRIMARY KEY,
    NAME VARCHAR(155),
    POSITION VARCHAR(155),
    SALARY INT,
    ID_DEPARTMENT INT,
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT(ID_DEPARTMENT)
);


-- Table Project
CREATE TABLE PROJECT (
    ID_PROJECT INT PRIMARY KEY,
    NAME VARCHAR(155),
    BUDGET INT
);

-- Table Employee-Project (Much to Much)
CREATE TABLE EMPLOYEE_PROJECT (
    ID_EMPLOYEE INT,
    ID_PROJECT INT,
    PRIMARY KEY (ID_EMPLOYEE, ID_PROJECT),
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID_EMPLOYEE),
    FOREIGN KEY (ID_PROJECT) REFERENCES PROJECT(ID_PROJECT)
);

-- Table Client
CREATE TABLE CLIENT (
    ID_CLIENT INT PRIMARY KEY,
    NAME VARCHAR(155),
    CONTACT VARCHAR(155)
);

-- Table Facture
CREATE TABLE FACTURE (
    ID_FACTURE INT PRIMARY KEY,
    ID_CLIENT INT,
    TOTAL INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

-- Table Product
CREATE TABLE PRODUCT (
    ID_PRODUCT INT PRIMARY KEY,
    NAME VARCHAR(155),
    PRICE INT,
    STOCK INT
);

-- Table Facture-Product (Much to Much)
CREATE TABLE FACTURE_PRODUCT (
    ID_FACTURE INT,
    ID_PRODUCT INT,
    PRIMARY KEY (ID_FACTURE, ID_PRODUCT),
    FOREIGN KEY (ID_FACTURE) REFERENCES FACTURE(ID_FACTURE),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

-- Table Supplier
CREATE TABLE SUPPLIER (
    ID_SUPPLIER INT PRIMARY KEY,
    NAME VARCHAR(155)
);

-- Table Supplier-Product (Much to Much)
CREATE TABLE SUPPLIER_PRODUCT (
    ID_SUPPLIER INT,
    ID_PRODUCT INT,
    PRIMARY KEY (ID_SUPPLIER, ID_PRODUCT),
    FOREIGN KEY (ID_SUPPLIER) REFERENCES SUPPLIER(ID_SUPPLIER),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
);

-- Table Inventory
CREATE TABLE INVENTORY (
    ID_INVENTORY INT PRIMARY KEY
);

-- Relation Inventory and Product
ALTER TABLE PRODUCT
ADD COLUMN ID_INVENTORY INT,
ADD FOREIGN KEY (ID_INVENTORY) REFERENCES INVENTORY(ID_INVENTORY);